
// GET
GET http://localhost:4000/api/ninjas

###
// POST
POST http://localhost:4000/api/ninjas
Content-Type: application/json

{
    "rank":"Yellow Belt",
    "available":true
}

###

// UPDATE
PUT http://localhost:4000/api/ninjas/1
Content-Type: application/json

{
    "name":"Edis",
    "rank":"Black Belt"
}

###

//update 
DELETE http://localhost:4000/api/ninjas/1
Content-Type: application/json 


###
