
// GET
GET http://localhost:4000/api/ninjas

###
// POST
POST http://localhost:4000/api/ninjas
Content-Type: "application/json"


###

// UPDATE
PUT http://localhost:4000/api/ninjas/1
Content-Type: application/json

{

}

###

//update 
DELETE http://localhost:4000/api/ninjas/1
Content-Type: application/json 

{

}

###
